### ISSUE TITLE
Payload too large error

### ISSUE THREAD

**Issue by atostaine** [worksofliam/rpgfreeweb#1]
Is there a limit to the number of lines that can be processed?

PayloadTooLargeError: request entity too large
    at readStream (C:\Users\atost\node_modules\raw-body\index.js:155:17)
    at getRawBody (C:\Users\atost\node_modules\raw-body\index.js:108:12)
    at read (C:\Users\atost\node_modules\body-parser\lib\read.js:77:3)
    at jsonParser (C:\Users\atost\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\Users\atost\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\atost\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\atost\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\atost\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\atost\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\atost\node_modules\express\lib\middleware\init.js:40:5)

**Comment by worksofliam** [comment]
Could be some simple changes to express server settings. Will investigate

**Comment by DavidShears** [comment]
Not the best solution, but changing index.js from:
app.use(bodyParser.json());
to:
app.use(bodyParser.json({limit: '1MB'}));

Allows me to process 10,000 odd lines of RPG (without it's bringing up the error by about 2,000 lines)
