### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by atostaine** [worksofliam/rpgfreeweb#2]
This line of code?

     c                   Movel     TimOut        WkTime4           4 0  

TypeError: Cannot read property 'name' of undefined
    at RPG.suggestMove (C:\Users\atost\rpg\RPG.js:64:30)
    at RPG.parse (C:\Users\atost\rpg\RPG.js:189:27)
    at C:\Users\atost\index.js:20:8
    at Layer.handle [as handle_request] (C:\Users\atost\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\atost\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\atost\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\atost\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\atost\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\atost\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\atost\node_modules\express\lib\router\index.js:275:10)

**Comment by worksofliam** [comment]
I'd give it another go and let me know.

**Comment by BrianGarland** [comment]
This one works for me using the current version

**Comment by worksofliam** [comment]
@BrianGarland 

Thanks!

I will close it then.
