### ISSUE TITLE
LastKey is not defined

### ISSUE THREAD

**Issue by atostaine** [worksofliam/rpgfreeweb#3]
ReferenceError: LastKey is not defined
    at Object.Parse (E:\RPGFreeWeb\rpgfreeweb\rpg\specs\C.js:53:23)
    at RPG.parse (E:\RPGFreeWeb\rpgfreeweb\rpg\RPG.js:221:30)
    at E:\RPGFreeWeb\rpgfreeweb\index.js:20:8
    at Layer.handle [as handle_request] (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\layer.js:95:5)
    at E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\index.js:335:12)
    at next (E:\RPGFreeWeb\rpgfreeweb\node_modules\express\lib\router\index.js:275:10)

Please advise if you need code sample to duplicate. THank you

**Comment by worksofliam** [comment]
Hi @atostaine 

yes please share a bit of sample code so I can recreate :)

**Comment by DavidShears** [comment]
I've found one scenario where I can repeat this:
1. node index
2. Open browser
3. Copy the attached three lines of code over the example code defined in index.html
4. Click convert

Specifically it looks like it's the third line that causes the error. Oddly if I convert the example code first, then try to convert these three lines it works. Possibly something is being "set on" in one scenario but not the other?

[snippet.txt](https://github.com/worksofliam/rpgfreeweb/files/3905194/snippet.txt)

**Comment by BrianGarland** [comment]
I can propose a fix that would stop it from blowing up, but there needs to be some major changes to the logic to make it convert things correctly since the PARM follows the CALL.  

My fix converts the CALL to a free form call and just leaves the PARM as is.   At least it doesn't blow up! 

@worksofliam should I do a pull request for this fix or do you want to hold off until a full fix can be done?
